spring:
  application:
    name: gaming-server-servicce-admin
  datasource:
    druid:
      url: jdbc:mysql://192.168.163.129:3306/ttms?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.bonc.ttms.gaming.server.domain.*.entity
  mapper-locations: classpath:mapper/**/*.xml

dubbo:
  scan:
    basePackages: com.bonc.ttms.gaming.server.service.admin.api.*.impl
  application:
    id: gaming-server-servicce-admin
    name: gaming-server-servicce-admin
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: zookeeper
    address: zookeeper://192.168.163.129:2181?backup=192.168.163.129:2182,192.168.163.129:2183

