server:
  port: 8100
spring:
  application:
    name: gaming-server-web-admin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html

dubbo:
  scan:
      basePackages: com.bonc.ttms.gaming.server.web.admin.*.controller
  application:
    id: gaming-server-web-admin
    name: gaming-server-web-admin
  registry:
      id: zookeeper
      address: zookeeper://192.168.163.129:2181?backup=192.168.163.129:2182,192.168.163.129:2183
